"""Shared configuration for the Desa Cantik Excel pipeline."""

SRC_SHEET = "1. list_data (ori)"
WILAYAH_SHEET = "kd wilayah"
QUALITY_SHEET = "Kode Kualitas"

DASHBOARD_RAW_SHEET = "Dashboard (Raw)"
DASHBOARD_CLEANED_SHEET = "Dashboard (Cleaned)"

SRC_HEADER_ROW = 7
SRC_DATA_START_ROW = 8

# Kolom mentah di sheet 1 (raw)
COL_KECAMATAN_RAW = 9  # I: "KECAMATAN SEKAYU"
COL_DESA_RAW = 10      # J: "DESA SUNGAI MEDAK"

# Kolom komoditas awalnya dicatat dari sheet "3.list_data (value)".
# Untuk membaca langsung dari sheet 1, posisinya digeser -7 kolom.
COL_SHIFT_SHEET3_TO_SHEET1 = -7

HEADERS = [
    "Id Kec Desa",
    "Kode Kecamatan",
    "Kecamatan",
    "Kode Desa",
    "Desa",
    "Id Komoditas",
    "Komoditas",
    "Id Kualitas",
    "Kualitas",
    "Satuan",
    "Harga",
    "Tanggal Pendataan",
    "Minggu",
    "No Bulan",
    "Bulan",
    "Periode",
    "No Periode",
    "Asal Barang",
    "Periode (Tahun-Bulan-Minggu)",
    "Tahun",
]

BULAN_ID = [
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
]
BULAN_ID_3 = [bulan[:3] for bulan in BULAN_ID]

BLOCKS = [
    dict(
        id_kom=1,
        nama="Beras",
        unit="kg",
        kualitas_col="X",
        harga_col="Y",
        tanggal_col="Z",
        asal_col="AA",
        choice_map={1: 1, 2: 3, 3: 18},
        choice_names={1: "Selancar", 2: "Topi Koki", 3: "Lainnya"},
    ),
    dict(
        id_kom=2,
        nama="Tepung terigu",
        unit="kg",
        kualitas_col="AB",
        harga_col="AC",
        tanggal_col="AD",
        asal_col="AE",
        choice_map={1: 4, 2: 5, 3: 6, 4: 19},
        choice_names={
            1: "Cakra Kembar",
            2: "Segitiga Kemasan",
            3: "Segitiga Biru Curah",
            4: "Lainnya",
        },
    ),
    dict(
        id_kom=3,
        nama="Minyak Goreng",
        unit="kg",
        kualitas_col="AF",
        harga_col="AG",
        tanggal_col="AH",
        asal_col="AI",
        choice_map={1: 7, 2: 8, 3: 9, 4: 20},
        choice_names={1: "Sunco", 2: "Fortune", 3: "Bimoli", 4: "Lainnya"},
    ),
    dict(
        id_kom=4,
        nama="Gula Pasir",
        unit="kg",
        kualitas_col="AJ",
        harga_col="AK",
        tanggal_col="AL",
        asal_col="AM",
        choice_map={1: 10, 2: 12, 3: 21},
        choice_names={1: "Curah", 2: "PSM", 3: "Lainnya"},
    ),
    dict(
        id_kom=5,
        nama="Mie Kering Instan",
        unit="bungkus",
        kualitas_col="AN",
        harga_col="AO",
        tanggal_col="AP",
        asal_col="AQ",
        choice_map={1: 13, 2: 23, 3: 24},
        choice_names={
            1: "Indomie Goreng",
            2: "Indomie Kari Ayam",
            3: "Mie sedap Goreng",
        },
    ),
    dict(
        id_kom=6,
        nama="Susu Bubuk Balita",
        unit="Kotak 400 Gram",
        kualitas_col="AR",
        harga_col="AS",
        tanggal_col="AT",
        asal_col="AU",
        choice_map={1: 25, 2: 26, 3: 27},
        choice_names={1: "Frisian Flag 123", 2: "Dancow 1+", 3: "Lainnya"},
    ),
    dict(
        id_kom=7,
        nama="Susu Bubuk",
        unit="Per-Kotak 400 Gram",
        kualitas_col="AV",
        harga_col="AW",
        tanggal_col="AX",
        asal_col="AY",
        choice_map={1: 28, 2: 29, 3: 30},
        choice_names={
            1: "Frisian Flag Full Cream",
            2: "Dancow Instant",
            3: "Lainnya",
        },
    ),
    dict(
        id_kom=8,
        nama="Cabai Merah",
        unit="kg",
        kualitas_col="AZ",
        harga_col="BA",
        tanggal_col="BB",
        asal_col="BC",
        choice_map={1: 31, 2: 32},
        choice_names={1: "Keriting Segar", 2: "Besar Segar"},
    ),
    dict(
        id_kom=9,
        nama="Cabai Rawit",
        unit="kg",
        kualitas_col=None,
        harga_col="BI",
        tanggal_col="BJ",
        asal_col="BK",
        fixed_h=33,
        fixed_i="Segar",
    ),
    dict(
        id_kom=10,
        nama="Daging Ayam Ras",
        unit="kg",
        kualitas_col=None,
        harga_col="BE",
        tanggal_col="BF",
        asal_col="BG",
        fixed_h=34,
        fixed_i="Segar",
    ),
    dict(
        id_kom=11,
        nama="Telur Ayam Ras",
        unit="kg",
        kualitas_col=None,
        harga_col="BM",
        tanggal_col="BN",
        asal_col="BO",
        fixed_h=35,
        fixed_i="Sedang",
    ),
    dict(
        id_kom=12,
        nama="Bawang Merah",
        unit="kg",
        kualitas_col=None,
        harga_col="BQ",
        tanggal_col="BR",
        asal_col="BS",
        fixed_h=36,
        fixed_i="Sedang",
    ),
    dict(
        id_kom=13,
        nama="Bawang Putih",
        unit="kg",
        kualitas_col=None,
        harga_col="BU",
        tanggal_col="BV",
        asal_col="BW",
        fixed_h=37,
        fixed_i="Sedang",
    ),
    dict(
        id_kom=14,
        nama="Daging Sapi",
        unit="kg",
        kualitas_col=None,
        harga_col="BY",
        tanggal_col="BZ",
        asal_col="CA",
        fixed_h=38,
        fixed_i="Segar",
    ),
    dict(
        id_kom=15,
        nama="Udang",
        unit="kg",
        kualitas_col=None,
        harga_col="CC",
        tanggal_col="CD",
        asal_col="CE",
        fixed_h=39,
        fixed_i="Sedang Segar",
    ),
    dict(
        id_kom=16,
        nama="Ikan Kembung",
        unit="kg",
        kualitas_col=None,
        harga_col="CG",
        tanggal_col="CH",
        asal_col="CI",
        fixed_h=40,
        fixed_i="Sedang Segar",
    ),
    dict(
        id_kom=17,
        nama="Tempe",
        unit="kg",
        kualitas_col=None,
        harga_col="CK",
        tanggal_col="CL",
        asal_col="CM",
        fixed_h=41,
        fixed_i="Putih Bersih",
    ),
    dict(
        id_kom=18,
        nama="Tahu Mentah",
        unit="kg",
        kualitas_col=None,
        harga_col="CO",
        tanggal_col="CP",
        asal_col="CQ",
        fixed_h=42,
        fixed_i="Putih Bersih",
    ),
    dict(
        id_kom=19,
        nama="Pisang",
        unit="kg",
        kualitas_col=None,
        harga_col="CS",
        tanggal_col="CT",
        asal_col="CU",
        fixed_h=43,
        fixed_i="Segar",
    ),
    dict(
        id_kom=20,
        nama="Jeruk",
        unit="kg",
        kualitas_col=None,
        harga_col="CW",
        tanggal_col="CX",
        asal_col="CY",
        fixed_h=44,
        fixed_i="Sedang Segar",
    ),
]
